language: node_js

node_js:
  - "node"

addons:
  ssh_known_hosts: nginxconfig.io

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

script:
  - npm run test

before_deploy:
  - openssl aes-256-cbc -K $encrypted_c855341ef4be_key -iv $encrypted_c855341ef4be_iv -in .deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    script: bash .travis_deploy.sh /var/www/nginxconfig.io/
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash .travis_deploy.sh var/www/beta.nginxconfig.io/
    skip_cleanup: true
    on:
      branch: beta
